// AUTO-GENERATED by tauri-specta. Do not edit by hand.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	newGame: (opts: NewGameOpts) => typedError<GameSnapshot, ApiError>(__TAURI_INVOKE("new_game", { opts })),
	legalMovesFrom: (gameId: string, square: string) => typedError<string[], ApiError>(__TAURI_INVOKE("legal_moves_from", { gameId, square })),
	makeMove: (gameId: string, from: string, to: string, promotion: "n" | "b" | "r" | "q" | null) => typedError<MoveResult, ApiError>(__TAURI_INVOKE("make_move", { gameId, from, to, promotion })),
	requestAiMove: (gameId: string) => typedError<null, ApiError>(__TAURI_INVOKE("request_ai_move", { gameId })),
	undoMove: (gameId: string) => typedError<GameSnapshot, ApiError>(__TAURI_INVOKE("undo_move", { gameId })),
	resign: (gameId: string) => typedError<GameSnapshot, ApiError>(__TAURI_INVOKE("resign", { gameId })),
	offerDraw: (gameId: string) => typedError<GameSnapshot, ApiError>(__TAURI_INVOKE("offer_draw", { gameId })),
	claimDraw: (gameId: string) => typedError<GameSnapshot, ApiError>(__TAURI_INVOKE("claim_draw", { gameId })),
	loadPgn: (pgn: string) => typedError<GameSnapshot, ApiError>(__TAURI_INVOKE("load_pgn", { pgn })),
	exportPgn: (gameId: string) => typedError<string, ApiError>(__TAURI_INVOKE("export_pgn", { gameId })),
	setClock: (gameId: string, timeControl: TimeControl) => typedError<GameSnapshot, ApiError>(__TAURI_INVOKE("set_clock", { gameId, timeControl })),
	pauseClock: (gameId: string) => typedError<GameSnapshot, ApiError>(__TAURI_INVOKE("pause_clock", { gameId })),
	resumeClock: (gameId: string) => typedError<GameSnapshot, ApiError>(__TAURI_INVOKE("resume_clock", { gameId })),
	getSettings: () => typedError<Settings, ApiError>(__TAURI_INVOKE("get_settings")),
	setSettings: (settings: Settings) => typedError<Settings, ApiError>(__TAURI_INVOKE("set_settings", { settings })),
};

/** Events */
export const events = {
	aiProgress: makeEvent<AiProgressEvent>("ai-progress"),
	clockTick: makeEvent<ClockTickEvent>("clock-tick"),
	gameOver: makeEvent<GameOverEvent>("game-over"),
	moveMade: makeEvent<MoveMadeEvent>("move-made"),
};

/* Types */
export type AiProgressEvent = {
	game_id: string,
	depth: number,
	eval_cp: number,
	pv_san: string[],
};

export type ApiError = { kind: "GameNotFound"; message: string } | { kind: "IllegalMove"; message: string } | { kind: "InvalidInput"; message: string } | { kind: "Engine"; message: string } | { kind: "Internal"; message: string };

export type BoardTheme = "wood" | "slate" | "wood_realistic" | "slate_realistic";

export type ClockState = {
	white_ms: number,
	black_ms: number,
	active: Color | null,
	paused: boolean,
};

export type ClockTickEvent = {
	game_id: string,
	white_ms: number,
	black_ms: number,
	active: Color | null,
};

export type Color = "w" | "b";

export type GameMode = 
// Human vs human (local).
"hvh" | 
// Human vs AI.
"hva";

export type GameOverEvent = {
	game_id: string,
	result: GameResult,
	reason: GameStatus,
};

export type GameResult = "white" | "black" | "draw" | "ongoing";

export type GameSnapshot = {
	game_id: string,
	fen: string,
	turn: Color,
	in_check: boolean,
	status: GameStatus,
	result: GameResult,
	history: Move[],
	// Map of source-square -> reachable target squares.
	legal_moves: { [key in string]: string[] },
	clock: ClockState | null,
	mode: GameMode,
	ai_difficulty: number | null,
	human_color: Color | null,
	last_move: Move | null,
};

export type GameStatus = "active" | "checkmate" | "stalemate" | "draw_fifty_move" | "draw_threefold" | "draw_insufficient" | "draw_agreement" | "resigned" | "time_forfeit";

export type HumanColorChoice = "w" | "b" | "random";

export type Move = {
	from: string,
	to: string,
	promotion: Promotion | null,
	san: string,
	uci: string,
	captured: Piece | null,
	is_check: boolean,
	is_mate: boolean,
	is_castle: boolean,
	is_en_passant: boolean,
};

export type MoveMadeEvent = {
	game_id: string,
	mv: Move,
	snapshot: GameSnapshot,
};

export type MoveResult = {
	mv: Move,
	snapshot: GameSnapshot,
};

export type NewGameOpts = {
	mode: GameMode,
	// Required when `mode == Hva`. Range 1..=10.
	ai_difficulty: number | null,
	human_color: HumanColorChoice | null,
	time_control: TimeControl | null,
};

export type Piece = {
	color: Color,
	kind: PieceKind,
};

export type PieceKind = "p" | "n" | "b" | "r" | "q" | "k";

export type PieceSet = "classic" | "modern" | "merida" | "minimal";

export type Promotion = "n" | "b" | "r" | "q";

export type Settings = {
	board_theme: BoardTheme,
	piece_set: PieceSet,
	sound_enabled: boolean,
	sound_volume: number,
	show_legal_moves: boolean,
	show_coordinates: boolean,
	show_last_move: boolean,
};

export type TimeControl = {
	initial_ms: number,
	increment_ms: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

