// Placeholder — this file is auto-generated by tauri-specta on every debug
// build of the Rust backend (`cargo tauri dev` / `cargo tauri build`).
// Until the first build runs, the hand-authored types in `./contract.ts`
// are used by `./client.ts` and `./mock.ts`.

export {};
