// Hand-authored mirror of `src-tauri/src/api.rs`.
// Used by the frontend subagent during mock-mode development; replaced at
// runtime by `bindings.ts` (regenerated by tauri-specta on every backend build).
//
// IMPORTANT: keep field names and serde rename rules in sync with api.rs.

export type SquareStr = string; // "a1".."h8"
export type GameId = string;

export type Color = "w" | "b";
export type PieceKind = "p" | "n" | "b" | "r" | "q" | "k";
export type Promotion = "n" | "b" | "r" | "q";

export interface Piece {
  color: Color;
  kind: PieceKind;
}

export interface Move {
  from: SquareStr;
  to: SquareStr;
  promotion: Promotion | null;
  san: string;
  uci: string;
  captured: Piece | null;
  is_check: boolean;
  is_mate: boolean;
  is_castle: boolean;
  is_en_passant: boolean;
}

export type GameStatus =
  | "active"
  | "checkmate"
  | "stalemate"
  | "draw_fifty_move"
  | "draw_threefold"
  | "draw_insufficient"
  | "draw_agreement"
  | "resigned"
  | "time_forfeit";

export type GameResult = "white" | "black" | "draw" | "ongoing";

export interface ClockState {
  white_ms: number;
  black_ms: number;
  active: Color | null;
  paused: boolean;
}

export type GameMode = "hvh" | "hva";
export type HumanColorChoice = "w" | "b" | "random";

export interface TimeControl {
  initial_ms: number;
  increment_ms: number;
}

export interface NewGameOpts {
  mode: GameMode;
  ai_difficulty: number | null; // 1..=10 when mode === "hva"
  human_color: HumanColorChoice | null;
  time_control: TimeControl | null;
}

export interface GameSnapshot {
  game_id: GameId;
  fen: string;
  turn: Color;
  in_check: boolean;
  status: GameStatus;
  result: GameResult;
  history: Move[];
  legal_moves: Record<SquareStr, SquareStr[]>;
  clock: ClockState | null;
  mode: GameMode;
  ai_difficulty: number | null;
  human_color: Color | null;
  last_move: Move | null;
}

export interface MoveResult {
  mv: Move;
  snapshot: GameSnapshot;
}

export type BoardTheme = "wood" | "slate" | "wood_realistic" | "slate_realistic";
export type PieceSet = "classic" | "modern" | "merida" | "minimal";

export interface Settings {
  board_theme: BoardTheme;
  piece_set: PieceSet;
  sound_enabled: boolean;
  sound_volume: number;
  show_legal_moves: boolean;
  show_coordinates: boolean;
  show_last_move: boolean;
}

// Events ---------------------------------------------------------------------

export interface MoveMadeEvent {
  game_id: GameId;
  mv: Move;
  snapshot: GameSnapshot;
}

export interface AiProgressEvent {
  game_id: GameId;
  depth: number;
  eval_cp: number;
  pv_san: string[];
}

export interface GameOverEvent {
  game_id: GameId;
  result: GameResult;
  reason: GameStatus;
}

export interface ClockTickEvent {
  game_id: GameId;
  white_ms: number;
  black_ms: number;
  active: Color | null;
}

// Errors ---------------------------------------------------------------------

export type ApiError =
  | { kind: "GameNotFound"; message: string }
  | { kind: "IllegalMove"; message: string }
  | { kind: "InvalidInput"; message: string }
  | { kind: "Engine"; message: string }
  | { kind: "Internal"; message: string };
