// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One-time bootstrap. Dart calls this with the writable application
/// data directory (from `path_provider`) before issuing any command.
void bridgeInit({required String dataDir}) =>
    RustLib.instance.api.crateApiBridgeInit(dataDir: dataDir);

/// Subscribe to push events. flutter_rust_bridge turns
/// `StreamSink<BackendEvent>` into a Dart `Stream<BackendEvent>`.
Stream<BackendEvent> subscribeEvents() =>
    RustLib.instance.api.crateApiSubscribeEvents();

/// Override the Stockfish spawner with an explicit binary path. The
/// Flutter Android plugin code calls this after extracting the binary
/// out of `assets/stockfish/<abi>/stockfish`, chmod 0755'ing it.
///
/// No-op today: hot-swapping the spawner on a live session would
/// require a `SessionManager::replace_spawner` seam. We log and accept
/// silently; for now Android needs to stage the binary and call
/// [`bridge_init`] before the first AI request.
void bridgeProvideExternalStockfish({required String binaryPath}) =>
    RustLib.instance.api
        .crateApiBridgeProvideExternalStockfish(binaryPath: binaryPath);

Future<GameSnapshot> newGame({required NewGameOpts opts}) =>
    RustLib.instance.api.crateApiNewGame(opts: opts);

Future<List<String>> legalMovesFrom(
        {required String gameId, required String square}) =>
    RustLib.instance.api.crateApiLegalMovesFrom(gameId: gameId, square: square);

Future<MoveResult> makeMove(
        {required String gameId,
        required String from,
        required String to,
        Promotion? promotion}) =>
    RustLib.instance.api.crateApiMakeMove(
        gameId: gameId, from: from, to: to, promotion: promotion);

Future<void> requestAiMove({required String gameId}) =>
    RustLib.instance.api.crateApiRequestAiMove(gameId: gameId);

Future<GameSnapshot> undoMove({required String gameId}) =>
    RustLib.instance.api.crateApiUndoMove(gameId: gameId);

Future<GameSnapshot> resign({required String gameId}) =>
    RustLib.instance.api.crateApiResign(gameId: gameId);

Future<GameSnapshot> offerDraw({required String gameId}) =>
    RustLib.instance.api.crateApiOfferDraw(gameId: gameId);

Future<GameSnapshot> claimDraw({required String gameId}) =>
    RustLib.instance.api.crateApiClaimDraw(gameId: gameId);

Future<GameSnapshot> loadPgn({required String pgn}) =>
    RustLib.instance.api.crateApiLoadPgn(pgn: pgn);

Future<String> exportPgn({required String gameId}) =>
    RustLib.instance.api.crateApiExportPgn(gameId: gameId);

Future<GameSnapshot> setClock(
        {required String gameId, required TimeControl timeControl}) =>
    RustLib.instance.api
        .crateApiSetClock(gameId: gameId, timeControl: timeControl);

Future<GameSnapshot> pauseClock({required String gameId}) =>
    RustLib.instance.api.crateApiPauseClock(gameId: gameId);

Future<GameSnapshot> resumeClock({required String gameId}) =>
    RustLib.instance.api.crateApiResumeClock(gameId: gameId);

Future<Settings> getSettings() => RustLib.instance.api.crateApiGetSettings();

Future<Settings> setSettings({required Settings settings}) =>
    RustLib.instance.api.crateApiSetSettings(settings: settings);

/// Returns the current snapshot for a game, or `None` if it does not exist.
Future<GameSnapshot?> snapshot({required String gameId}) =>
    RustLib.instance.api.crateApiSnapshot(gameId: gameId);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiError>>
abstract class ApiError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BackendEvent>>
abstract class BackendEvent implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GameSnapshot>>
abstract class GameSnapshot implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MoveResult>>
abstract class MoveResult implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NewGameOpts>>
abstract class NewGameOpts implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Promotion>>
abstract class Promotion implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Settings>>
abstract class Settings implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TimeControl>>
abstract class TimeControl implements RustOpaqueInterface {}
