// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Map<String, List<String>> dco_decode_Map_String_list_String_None(dynamic raw);

  @protected
  RustStreamSink<BackendEvent> dco_decode_StreamSink_backend_event_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Accent dco_decode_accent(dynamic raw);

  @protected
  AiProgressEvent dco_decode_ai_progress_event(dynamic raw);

  @protected
  ApiError dco_decode_api_error(dynamic raw);

  @protected
  AppTheme dco_decode_app_theme(dynamic raw);

  @protected
  BackendEvent dco_decode_backend_event(dynamic raw);

  @protected
  BoardTheme dco_decode_board_theme(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AiProgressEvent dco_decode_box_autoadd_ai_progress_event(dynamic raw);

  @protected
  ClockState dco_decode_box_autoadd_clock_state(dynamic raw);

  @protected
  ClockTickEvent dco_decode_box_autoadd_clock_tick_event(dynamic raw);

  @protected
  Color dco_decode_box_autoadd_color(dynamic raw);

  @protected
  GameOverEvent dco_decode_box_autoadd_game_over_event(dynamic raw);

  @protected
  GameSnapshot dco_decode_box_autoadd_game_snapshot(dynamic raw);

  @protected
  HumanColorChoice dco_decode_box_autoadd_human_color_choice(dynamic raw);

  @protected
  Move dco_decode_box_autoadd_move(dynamic raw);

  @protected
  MoveMadeEvent dco_decode_box_autoadd_move_made_event(dynamic raw);

  @protected
  NewGameOpts dco_decode_box_autoadd_new_game_opts(dynamic raw);

  @protected
  Piece dco_decode_box_autoadd_piece(dynamic raw);

  @protected
  Promotion dco_decode_box_autoadd_promotion(dynamic raw);

  @protected
  Settings dco_decode_box_autoadd_settings(dynamic raw);

  @protected
  TimeControl dco_decode_box_autoadd_time_control(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  ClockState dco_decode_clock_state(dynamic raw);

  @protected
  ClockTickEvent dco_decode_clock_tick_event(dynamic raw);

  @protected
  Color dco_decode_color(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  GameMode dco_decode_game_mode(dynamic raw);

  @protected
  GameOverEvent dco_decode_game_over_event(dynamic raw);

  @protected
  GameResult dco_decode_game_result(dynamic raw);

  @protected
  GameSnapshot dco_decode_game_snapshot(dynamic raw);

  @protected
  GameStatus dco_decode_game_status(dynamic raw);

  @protected
  HumanColorChoice dco_decode_human_color_choice(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Move> dco_decode_list_move(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, List<String>)> dco_decode_list_record_string_list_string(
      dynamic raw);

  @protected
  Move dco_decode_move(dynamic raw);

  @protected
  MoveMadeEvent dco_decode_move_made_event(dynamic raw);

  @protected
  MoveResult dco_decode_move_result(dynamic raw);

  @protected
  NewGameOpts dco_decode_new_game_opts(dynamic raw);

  @protected
  ClockState? dco_decode_opt_box_autoadd_clock_state(dynamic raw);

  @protected
  Color? dco_decode_opt_box_autoadd_color(dynamic raw);

  @protected
  GameSnapshot? dco_decode_opt_box_autoadd_game_snapshot(dynamic raw);

  @protected
  HumanColorChoice? dco_decode_opt_box_autoadd_human_color_choice(dynamic raw);

  @protected
  Move? dco_decode_opt_box_autoadd_move(dynamic raw);

  @protected
  Piece? dco_decode_opt_box_autoadd_piece(dynamic raw);

  @protected
  Promotion? dco_decode_opt_box_autoadd_promotion(dynamic raw);

  @protected
  TimeControl? dco_decode_opt_box_autoadd_time_control(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  Piece dco_decode_piece(dynamic raw);

  @protected
  PieceKind dco_decode_piece_kind(dynamic raw);

  @protected
  PieceSet dco_decode_piece_set(dynamic raw);

  @protected
  Promotion dco_decode_promotion(dynamic raw);

  @protected
  (String, List<String>) dco_decode_record_string_list_string(dynamic raw);

  @protected
  Settings dco_decode_settings(dynamic raw);

  @protected
  TimeControl dco_decode_time_control(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Map<String, List<String>> sse_decode_Map_String_list_String_None(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<BackendEvent> sse_decode_StreamSink_backend_event_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Accent sse_decode_accent(SseDeserializer deserializer);

  @protected
  AiProgressEvent sse_decode_ai_progress_event(SseDeserializer deserializer);

  @protected
  ApiError sse_decode_api_error(SseDeserializer deserializer);

  @protected
  AppTheme sse_decode_app_theme(SseDeserializer deserializer);

  @protected
  BackendEvent sse_decode_backend_event(SseDeserializer deserializer);

  @protected
  BoardTheme sse_decode_board_theme(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AiProgressEvent sse_decode_box_autoadd_ai_progress_event(
      SseDeserializer deserializer);

  @protected
  ClockState sse_decode_box_autoadd_clock_state(SseDeserializer deserializer);

  @protected
  ClockTickEvent sse_decode_box_autoadd_clock_tick_event(
      SseDeserializer deserializer);

  @protected
  Color sse_decode_box_autoadd_color(SseDeserializer deserializer);

  @protected
  GameOverEvent sse_decode_box_autoadd_game_over_event(
      SseDeserializer deserializer);

  @protected
  GameSnapshot sse_decode_box_autoadd_game_snapshot(
      SseDeserializer deserializer);

  @protected
  HumanColorChoice sse_decode_box_autoadd_human_color_choice(
      SseDeserializer deserializer);

  @protected
  Move sse_decode_box_autoadd_move(SseDeserializer deserializer);

  @protected
  MoveMadeEvent sse_decode_box_autoadd_move_made_event(
      SseDeserializer deserializer);

  @protected
  NewGameOpts sse_decode_box_autoadd_new_game_opts(
      SseDeserializer deserializer);

  @protected
  Piece sse_decode_box_autoadd_piece(SseDeserializer deserializer);

  @protected
  Promotion sse_decode_box_autoadd_promotion(SseDeserializer deserializer);

  @protected
  Settings sse_decode_box_autoadd_settings(SseDeserializer deserializer);

  @protected
  TimeControl sse_decode_box_autoadd_time_control(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  ClockState sse_decode_clock_state(SseDeserializer deserializer);

  @protected
  ClockTickEvent sse_decode_clock_tick_event(SseDeserializer deserializer);

  @protected
  Color sse_decode_color(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  GameMode sse_decode_game_mode(SseDeserializer deserializer);

  @protected
  GameOverEvent sse_decode_game_over_event(SseDeserializer deserializer);

  @protected
  GameResult sse_decode_game_result(SseDeserializer deserializer);

  @protected
  GameSnapshot sse_decode_game_snapshot(SseDeserializer deserializer);

  @protected
  GameStatus sse_decode_game_status(SseDeserializer deserializer);

  @protected
  HumanColorChoice sse_decode_human_color_choice(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Move> sse_decode_list_move(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, List<String>)> sse_decode_list_record_string_list_string(
      SseDeserializer deserializer);

  @protected
  Move sse_decode_move(SseDeserializer deserializer);

  @protected
  MoveMadeEvent sse_decode_move_made_event(SseDeserializer deserializer);

  @protected
  MoveResult sse_decode_move_result(SseDeserializer deserializer);

  @protected
  NewGameOpts sse_decode_new_game_opts(SseDeserializer deserializer);

  @protected
  ClockState? sse_decode_opt_box_autoadd_clock_state(
      SseDeserializer deserializer);

  @protected
  Color? sse_decode_opt_box_autoadd_color(SseDeserializer deserializer);

  @protected
  GameSnapshot? sse_decode_opt_box_autoadd_game_snapshot(
      SseDeserializer deserializer);

  @protected
  HumanColorChoice? sse_decode_opt_box_autoadd_human_color_choice(
      SseDeserializer deserializer);

  @protected
  Move? sse_decode_opt_box_autoadd_move(SseDeserializer deserializer);

  @protected
  Piece? sse_decode_opt_box_autoadd_piece(SseDeserializer deserializer);

  @protected
  Promotion? sse_decode_opt_box_autoadd_promotion(SseDeserializer deserializer);

  @protected
  TimeControl? sse_decode_opt_box_autoadd_time_control(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  Piece sse_decode_piece(SseDeserializer deserializer);

  @protected
  PieceKind sse_decode_piece_kind(SseDeserializer deserializer);

  @protected
  PieceSet sse_decode_piece_set(SseDeserializer deserializer);

  @protected
  Promotion sse_decode_promotion(SseDeserializer deserializer);

  @protected
  (String, List<String>) sse_decode_record_string_list_string(
      SseDeserializer deserializer);

  @protected
  Settings sse_decode_settings(SseDeserializer deserializer);

  @protected
  TimeControl sse_decode_time_control(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_list_String_None(
      Map<String, List<String>> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_backend_event_Sse(
      RustStreamSink<BackendEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_accent(Accent self, SseSerializer serializer);

  @protected
  void sse_encode_ai_progress_event(
      AiProgressEvent self, SseSerializer serializer);

  @protected
  void sse_encode_api_error(ApiError self, SseSerializer serializer);

  @protected
  void sse_encode_app_theme(AppTheme self, SseSerializer serializer);

  @protected
  void sse_encode_backend_event(BackendEvent self, SseSerializer serializer);

  @protected
  void sse_encode_board_theme(BoardTheme self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ai_progress_event(
      AiProgressEvent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_clock_state(
      ClockState self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_clock_tick_event(
      ClockTickEvent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_color(Color self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_game_over_event(
      GameOverEvent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_game_snapshot(
      GameSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_human_color_choice(
      HumanColorChoice self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_move(Move self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_move_made_event(
      MoveMadeEvent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_new_game_opts(
      NewGameOpts self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_piece(Piece self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_promotion(
      Promotion self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_settings(Settings self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_time_control(
      TimeControl self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_clock_state(ClockState self, SseSerializer serializer);

  @protected
  void sse_encode_clock_tick_event(
      ClockTickEvent self, SseSerializer serializer);

  @protected
  void sse_encode_color(Color self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_game_mode(GameMode self, SseSerializer serializer);

  @protected
  void sse_encode_game_over_event(GameOverEvent self, SseSerializer serializer);

  @protected
  void sse_encode_game_result(GameResult self, SseSerializer serializer);

  @protected
  void sse_encode_game_snapshot(GameSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_game_status(GameStatus self, SseSerializer serializer);

  @protected
  void sse_encode_human_color_choice(
      HumanColorChoice self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_move(List<Move> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_list_string(
      List<(String, List<String>)> self, SseSerializer serializer);

  @protected
  void sse_encode_move(Move self, SseSerializer serializer);

  @protected
  void sse_encode_move_made_event(MoveMadeEvent self, SseSerializer serializer);

  @protected
  void sse_encode_move_result(MoveResult self, SseSerializer serializer);

  @protected
  void sse_encode_new_game_opts(NewGameOpts self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_clock_state(
      ClockState? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_color(Color? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_game_snapshot(
      GameSnapshot? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_human_color_choice(
      HumanColorChoice? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_move(Move? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_piece(Piece? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_promotion(
      Promotion? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_time_control(
      TimeControl? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_piece(Piece self, SseSerializer serializer);

  @protected
  void sse_encode_piece_kind(PieceKind self, SseSerializer serializer);

  @protected
  void sse_encode_piece_set(PieceSet self, SseSerializer serializer);

  @protected
  void sse_encode_promotion(Promotion self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_list_string(
      (String, List<String>) self, SseSerializer serializer);

  @protected
  void sse_encode_settings(Settings self, SseSerializer serializer);

  @protected
  void sse_encode_time_control(TimeControl self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
