// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -826527510;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'chess_bridge',
    ioDirectory: '../crates/chess_bridge/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  void crateApiBridgeInit({required String dataDir});

  void crateApiBridgeProvideExternalStockfish({required String binaryPath});

  Future<GameSnapshot> crateApiClaimDraw({required String gameId});

  Future<String> crateApiExportPgn({required String gameId});

  Future<Settings> crateApiGetSettings();

  Future<List<String>> crateApiLegalMovesFrom(
      {required String gameId, required String square});

  Future<GameSnapshot> crateApiLoadPgn({required String pgn});

  Future<MoveResult> crateApiMakeMove(
      {required String gameId,
      required String from,
      required String to,
      Promotion? promotion});

  Future<GameSnapshot> crateApiNewGame({required NewGameOpts opts});

  Future<GameSnapshot> crateApiOfferDraw({required String gameId});

  Future<GameSnapshot> crateApiPauseClock({required String gameId});

  Future<void> crateApiRequestAiMove({required String gameId});

  Future<GameSnapshot> crateApiResign({required String gameId});

  Future<GameSnapshot> crateApiResumeClock({required String gameId});

  Future<GameSnapshot> crateApiSetClock(
      {required String gameId, required TimeControl timeControl});

  Future<Settings> crateApiSetSettings({required Settings settings});

  Future<GameSnapshot?> crateApiSnapshot({required String gameId});

  Stream<BackendEvent> crateApiSubscribeEvents();

  Future<GameSnapshot> crateApiUndoMove({required String gameId});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiBridgeInit({required String dataDir}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dataDir, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeInitConstMeta,
      argValues: [dataDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBridgeInitConstMeta => const TaskConstMeta(
        debugName: "bridge_init",
        argNames: ["dataDir"],
      );

  @override
  void crateApiBridgeProvideExternalStockfish({required String binaryPath}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(binaryPath, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeProvideExternalStockfishConstMeta,
      argValues: [binaryPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBridgeProvideExternalStockfishConstMeta =>
      const TaskConstMeta(
        debugName: "bridge_provide_external_stockfish",
        argNames: ["binaryPath"],
      );

  @override
  Future<GameSnapshot> crateApiClaimDraw({required String gameId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gameId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_game_snapshot,
        decodeErrorData: sse_decode_api_error,
      ),
      constMeta: kCrateApiClaimDrawConstMeta,
      argValues: [gameId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClaimDrawConstMeta => const TaskConstMeta(
        debugName: "claim_draw",
        argNames: ["gameId"],
      );

  @override
  Future<String> crateApiExportPgn({required String gameId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gameId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_api_error,
      ),
      constMeta: kCrateApiExportPgnConstMeta,
      argValues: [gameId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExportPgnConstMeta => const TaskConstMeta(
        debugName: "export_pgn",
        argNames: ["gameId"],
      );

  @override
  Future<Settings> crateApiGetSettings() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_settings,
        decodeErrorData: sse_decode_api_error,
      ),
      constMeta: kCrateApiGetSettingsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetSettingsConstMeta => const TaskConstMeta(
        debugName: "get_settings",
        argNames: [],
      );

  @override
  Future<List<String>> crateApiLegalMovesFrom(
      {required String gameId, required String square}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gameId, serializer);
        sse_encode_String(square, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_api_error,
      ),
      constMeta: kCrateApiLegalMovesFromConstMeta,
      argValues: [gameId, square],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLegalMovesFromConstMeta => const TaskConstMeta(
        debugName: "legal_moves_from",
        argNames: ["gameId", "square"],
      );

  @override
  Future<GameSnapshot> crateApiLoadPgn({required String pgn}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(pgn, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_game_snapshot,
        decodeErrorData: sse_decode_api_error,
      ),
      constMeta: kCrateApiLoadPgnConstMeta,
      argValues: [pgn],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoadPgnConstMeta => const TaskConstMeta(
        debugName: "load_pgn",
        argNames: ["pgn"],
      );

  @override
  Future<MoveResult> crateApiMakeMove(
      {required String gameId,
      required String from,
      required String to,
      Promotion? promotion}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gameId, serializer);
        sse_encode_String(from, serializer);
        sse_encode_String(to, serializer);
        sse_encode_opt_box_autoadd_promotion(promotion, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_move_result,
        decodeErrorData: sse_decode_api_error,
      ),
      constMeta: kCrateApiMakeMoveConstMeta,
      argValues: [gameId, from, to, promotion],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMakeMoveConstMeta => const TaskConstMeta(
        debugName: "make_move",
        argNames: ["gameId", "from", "to", "promotion"],
      );

  @override
  Future<GameSnapshot> crateApiNewGame({required NewGameOpts opts}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_new_game_opts(opts, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_game_snapshot,
        decodeErrorData: sse_decode_api_error,
      ),
      constMeta: kCrateApiNewGameConstMeta,
      argValues: [opts],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNewGameConstMeta => const TaskConstMeta(
        debugName: "new_game",
        argNames: ["opts"],
      );

  @override
  Future<GameSnapshot> crateApiOfferDraw({required String gameId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gameId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_game_snapshot,
        decodeErrorData: sse_decode_api_error,
      ),
      constMeta: kCrateApiOfferDrawConstMeta,
      argValues: [gameId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOfferDrawConstMeta => const TaskConstMeta(
        debugName: "offer_draw",
        argNames: ["gameId"],
      );

  @override
  Future<GameSnapshot> crateApiPauseClock({required String gameId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gameId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_game_snapshot,
        decodeErrorData: sse_decode_api_error,
      ),
      constMeta: kCrateApiPauseClockConstMeta,
      argValues: [gameId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPauseClockConstMeta => const TaskConstMeta(
        debugName: "pause_clock",
        argNames: ["gameId"],
      );

  @override
  Future<void> crateApiRequestAiMove({required String gameId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gameId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_api_error,
      ),
      constMeta: kCrateApiRequestAiMoveConstMeta,
      argValues: [gameId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRequestAiMoveConstMeta => const TaskConstMeta(
        debugName: "request_ai_move",
        argNames: ["gameId"],
      );

  @override
  Future<GameSnapshot> crateApiResign({required String gameId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gameId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_game_snapshot,
        decodeErrorData: sse_decode_api_error,
      ),
      constMeta: kCrateApiResignConstMeta,
      argValues: [gameId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiResignConstMeta => const TaskConstMeta(
        debugName: "resign",
        argNames: ["gameId"],
      );

  @override
  Future<GameSnapshot> crateApiResumeClock({required String gameId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gameId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_game_snapshot,
        decodeErrorData: sse_decode_api_error,
      ),
      constMeta: kCrateApiResumeClockConstMeta,
      argValues: [gameId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiResumeClockConstMeta => const TaskConstMeta(
        debugName: "resume_clock",
        argNames: ["gameId"],
      );

  @override
  Future<GameSnapshot> crateApiSetClock(
      {required String gameId, required TimeControl timeControl}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gameId, serializer);
        sse_encode_box_autoadd_time_control(timeControl, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_game_snapshot,
        decodeErrorData: sse_decode_api_error,
      ),
      constMeta: kCrateApiSetClockConstMeta,
      argValues: [gameId, timeControl],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSetClockConstMeta => const TaskConstMeta(
        debugName: "set_clock",
        argNames: ["gameId", "timeControl"],
      );

  @override
  Future<Settings> crateApiSetSettings({required Settings settings}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_settings(settings, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_settings,
        decodeErrorData: sse_decode_api_error,
      ),
      constMeta: kCrateApiSetSettingsConstMeta,
      argValues: [settings],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSetSettingsConstMeta => const TaskConstMeta(
        debugName: "set_settings",
        argNames: ["settings"],
      );

  @override
  Future<GameSnapshot?> crateApiSnapshot({required String gameId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gameId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_game_snapshot,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSnapshotConstMeta,
      argValues: [gameId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSnapshotConstMeta => const TaskConstMeta(
        debugName: "snapshot",
        argNames: ["gameId"],
      );

  @override
  Stream<BackendEvent> crateApiSubscribeEvents() {
    final sink = RustStreamSink<BackendEvent>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_backend_event_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSubscribeEventsConstMeta,
      argValues: [sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSubscribeEventsConstMeta => const TaskConstMeta(
        debugName: "subscribe_events",
        argNames: ["sink"],
      );

  @override
  Future<GameSnapshot> crateApiUndoMove({required String gameId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gameId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_game_snapshot,
        decodeErrorData: sse_decode_api_error,
      ),
      constMeta: kCrateApiUndoMoveConstMeta,
      argValues: [gameId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUndoMoveConstMeta => const TaskConstMeta(
        debugName: "undo_move",
        argNames: ["gameId"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Map<String, List<String>> dco_decode_Map_String_list_String_None(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(dco_decode_list_record_string_list_string(raw)
        .map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  RustStreamSink<BackendEvent> dco_decode_StreamSink_backend_event_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Accent dco_decode_accent(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Accent.values[raw as int];
  }

  @protected
  AiProgressEvent dco_decode_ai_progress_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AiProgressEvent(
      gameId: dco_decode_String(arr[0]),
      depth: dco_decode_u_32(arr[1]),
      evalCp: dco_decode_i_32(arr[2]),
      pvSan: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  ApiError dco_decode_api_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ApiError_GameNotFound(
          dco_decode_String(raw[1]),
        );
      case 1:
        return ApiError_IllegalMove(
          dco_decode_String(raw[1]),
        );
      case 2:
        return ApiError_InvalidInput(
          dco_decode_String(raw[1]),
        );
      case 3:
        return ApiError_Engine(
          dco_decode_String(raw[1]),
        );
      case 4:
        return ApiError_Internal(
          dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  AppTheme dco_decode_app_theme(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AppTheme.values[raw as int];
  }

  @protected
  BackendEvent dco_decode_backend_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return BackendEvent_MoveMade(
          dco_decode_box_autoadd_move_made_event(raw[1]),
        );
      case 1:
        return BackendEvent_AiProgress(
          dco_decode_box_autoadd_ai_progress_event(raw[1]),
        );
      case 2:
        return BackendEvent_GameOver(
          dco_decode_box_autoadd_game_over_event(raw[1]),
        );
      case 3:
        return BackendEvent_ClockTick(
          dco_decode_box_autoadd_clock_tick_event(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  BoardTheme dco_decode_board_theme(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BoardTheme.values[raw as int];
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AiProgressEvent dco_decode_box_autoadd_ai_progress_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ai_progress_event(raw);
  }

  @protected
  ClockState dco_decode_box_autoadd_clock_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_clock_state(raw);
  }

  @protected
  ClockTickEvent dco_decode_box_autoadd_clock_tick_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_clock_tick_event(raw);
  }

  @protected
  Color dco_decode_box_autoadd_color(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_color(raw);
  }

  @protected
  GameOverEvent dco_decode_box_autoadd_game_over_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_game_over_event(raw);
  }

  @protected
  GameSnapshot dco_decode_box_autoadd_game_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_game_snapshot(raw);
  }

  @protected
  HumanColorChoice dco_decode_box_autoadd_human_color_choice(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_human_color_choice(raw);
  }

  @protected
  Move dco_decode_box_autoadd_move(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_move(raw);
  }

  @protected
  MoveMadeEvent dco_decode_box_autoadd_move_made_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_move_made_event(raw);
  }

  @protected
  NewGameOpts dco_decode_box_autoadd_new_game_opts(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_new_game_opts(raw);
  }

  @protected
  Piece dco_decode_box_autoadd_piece(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_piece(raw);
  }

  @protected
  Promotion dco_decode_box_autoadd_promotion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_promotion(raw);
  }

  @protected
  Settings dco_decode_box_autoadd_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_settings(raw);
  }

  @protected
  TimeControl dco_decode_box_autoadd_time_control(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_time_control(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ClockState dco_decode_clock_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ClockState(
      whiteMs: dco_decode_u_64(arr[0]),
      blackMs: dco_decode_u_64(arr[1]),
      active: dco_decode_opt_box_autoadd_color(arr[2]),
      paused: dco_decode_bool(arr[3]),
    );
  }

  @protected
  ClockTickEvent dco_decode_clock_tick_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ClockTickEvent(
      gameId: dco_decode_String(arr[0]),
      whiteMs: dco_decode_u_64(arr[1]),
      blackMs: dco_decode_u_64(arr[2]),
      active: dco_decode_opt_box_autoadd_color(arr[3]),
    );
  }

  @protected
  Color dco_decode_color(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Color.values[raw as int];
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GameMode dco_decode_game_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GameMode.values[raw as int];
  }

  @protected
  GameOverEvent dco_decode_game_over_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return GameOverEvent(
      gameId: dco_decode_String(arr[0]),
      result: dco_decode_game_result(arr[1]),
      reason: dco_decode_game_status(arr[2]),
    );
  }

  @protected
  GameResult dco_decode_game_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GameResult.values[raw as int];
  }

  @protected
  GameSnapshot dco_decode_game_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return GameSnapshot(
      gameId: dco_decode_String(arr[0]),
      fen: dco_decode_String(arr[1]),
      turn: dco_decode_color(arr[2]),
      inCheck: dco_decode_bool(arr[3]),
      status: dco_decode_game_status(arr[4]),
      result: dco_decode_game_result(arr[5]),
      history: dco_decode_list_move(arr[6]),
      legalMoves: dco_decode_Map_String_list_String_None(arr[7]),
      clock: dco_decode_opt_box_autoadd_clock_state(arr[8]),
      mode: dco_decode_game_mode(arr[9]),
      aiDifficulty: dco_decode_opt_box_autoadd_u_8(arr[10]),
      humanColor: dco_decode_opt_box_autoadd_color(arr[11]),
      lastMove: dco_decode_opt_box_autoadd_move(arr[12]),
    );
  }

  @protected
  GameStatus dco_decode_game_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GameStatus.values[raw as int];
  }

  @protected
  HumanColorChoice dco_decode_human_color_choice(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HumanColorChoice.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Move> dco_decode_list_move(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_move).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, List<String>)> dco_decode_list_record_string_list_string(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_string_list_string)
        .toList();
  }

  @protected
  Move dco_decode_move(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return Move(
      from: dco_decode_String(arr[0]),
      to: dco_decode_String(arr[1]),
      promotion: dco_decode_opt_box_autoadd_promotion(arr[2]),
      san: dco_decode_String(arr[3]),
      uci: dco_decode_String(arr[4]),
      captured: dco_decode_opt_box_autoadd_piece(arr[5]),
      isCheck: dco_decode_bool(arr[6]),
      isMate: dco_decode_bool(arr[7]),
      isCastle: dco_decode_bool(arr[8]),
      isEnPassant: dco_decode_bool(arr[9]),
    );
  }

  @protected
  MoveMadeEvent dco_decode_move_made_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MoveMadeEvent(
      gameId: dco_decode_String(arr[0]),
      mv: dco_decode_move(arr[1]),
      snapshot: dco_decode_game_snapshot(arr[2]),
    );
  }

  @protected
  MoveResult dco_decode_move_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MoveResult(
      mv: dco_decode_move(arr[0]),
      snapshot: dco_decode_game_snapshot(arr[1]),
    );
  }

  @protected
  NewGameOpts dco_decode_new_game_opts(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NewGameOpts(
      mode: dco_decode_game_mode(arr[0]),
      aiDifficulty: dco_decode_opt_box_autoadd_u_8(arr[1]),
      humanColor: dco_decode_opt_box_autoadd_human_color_choice(arr[2]),
      timeControl: dco_decode_opt_box_autoadd_time_control(arr[3]),
    );
  }

  @protected
  ClockState? dco_decode_opt_box_autoadd_clock_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_clock_state(raw);
  }

  @protected
  Color? dco_decode_opt_box_autoadd_color(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_color(raw);
  }

  @protected
  GameSnapshot? dco_decode_opt_box_autoadd_game_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_game_snapshot(raw);
  }

  @protected
  HumanColorChoice? dco_decode_opt_box_autoadd_human_color_choice(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_human_color_choice(raw);
  }

  @protected
  Move? dco_decode_opt_box_autoadd_move(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_move(raw);
  }

  @protected
  Piece? dco_decode_opt_box_autoadd_piece(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_piece(raw);
  }

  @protected
  Promotion? dco_decode_opt_box_autoadd_promotion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_promotion(raw);
  }

  @protected
  TimeControl? dco_decode_opt_box_autoadd_time_control(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_time_control(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_8(raw);
  }

  @protected
  Piece dco_decode_piece(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Piece(
      color: dco_decode_color(arr[0]),
      kind: dco_decode_piece_kind(arr[1]),
    );
  }

  @protected
  PieceKind dco_decode_piece_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PieceKind.values[raw as int];
  }

  @protected
  PieceSet dco_decode_piece_set(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PieceSet.values[raw as int];
  }

  @protected
  Promotion dco_decode_promotion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Promotion.values[raw as int];
  }

  @protected
  (String, List<String>) dco_decode_record_string_list_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_list_String(arr[1]),
    );
  }

  @protected
  Settings dco_decode_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return Settings(
      appTheme: dco_decode_app_theme(arr[0]),
      boardTheme: dco_decode_board_theme(arr[1]),
      pieceSet: dco_decode_piece_set(arr[2]),
      accent: dco_decode_accent(arr[3]),
      soundEnabled: dco_decode_bool(arr[4]),
      soundVolume: dco_decode_f_32(arr[5]),
      showLegalMoves: dco_decode_bool(arr[6]),
      showCoordinates: dco_decode_bool(arr[7]),
      showLastMove: dco_decode_bool(arr[8]),
    );
  }

  @protected
  TimeControl dco_decode_time_control(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TimeControl(
      initialMs: dco_decode_u_64(arr[0]),
      incrementMs: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Map<String, List<String>> sse_decode_Map_String_list_String_None(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_list_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  RustStreamSink<BackendEvent> sse_decode_StreamSink_backend_event_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Accent sse_decode_accent(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Accent.values[inner];
  }

  @protected
  AiProgressEvent sse_decode_ai_progress_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gameId = sse_decode_String(deserializer);
    var var_depth = sse_decode_u_32(deserializer);
    var var_evalCp = sse_decode_i_32(deserializer);
    var var_pvSan = sse_decode_list_String(deserializer);
    return AiProgressEvent(
        gameId: var_gameId,
        depth: var_depth,
        evalCp: var_evalCp,
        pvSan: var_pvSan);
  }

  @protected
  ApiError sse_decode_api_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return ApiError_GameNotFound(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return ApiError_IllegalMove(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return ApiError_InvalidInput(var_field0);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return ApiError_Engine(var_field0);
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return ApiError_Internal(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  AppTheme sse_decode_app_theme(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return AppTheme.values[inner];
  }

  @protected
  BackendEvent sse_decode_backend_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_move_made_event(deserializer);
        return BackendEvent_MoveMade(var_field0);
      case 1:
        var var_field0 = sse_decode_box_autoadd_ai_progress_event(deserializer);
        return BackendEvent_AiProgress(var_field0);
      case 2:
        var var_field0 = sse_decode_box_autoadd_game_over_event(deserializer);
        return BackendEvent_GameOver(var_field0);
      case 3:
        var var_field0 = sse_decode_box_autoadd_clock_tick_event(deserializer);
        return BackendEvent_ClockTick(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  BoardTheme sse_decode_board_theme(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BoardTheme.values[inner];
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AiProgressEvent sse_decode_box_autoadd_ai_progress_event(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ai_progress_event(deserializer));
  }

  @protected
  ClockState sse_decode_box_autoadd_clock_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_clock_state(deserializer));
  }

  @protected
  ClockTickEvent sse_decode_box_autoadd_clock_tick_event(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_clock_tick_event(deserializer));
  }

  @protected
  Color sse_decode_box_autoadd_color(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_color(deserializer));
  }

  @protected
  GameOverEvent sse_decode_box_autoadd_game_over_event(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_game_over_event(deserializer));
  }

  @protected
  GameSnapshot sse_decode_box_autoadd_game_snapshot(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_game_snapshot(deserializer));
  }

  @protected
  HumanColorChoice sse_decode_box_autoadd_human_color_choice(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_human_color_choice(deserializer));
  }

  @protected
  Move sse_decode_box_autoadd_move(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_move(deserializer));
  }

  @protected
  MoveMadeEvent sse_decode_box_autoadd_move_made_event(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_move_made_event(deserializer));
  }

  @protected
  NewGameOpts sse_decode_box_autoadd_new_game_opts(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_new_game_opts(deserializer));
  }

  @protected
  Piece sse_decode_box_autoadd_piece(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_piece(deserializer));
  }

  @protected
  Promotion sse_decode_box_autoadd_promotion(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_promotion(deserializer));
  }

  @protected
  Settings sse_decode_box_autoadd_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_settings(deserializer));
  }

  @protected
  TimeControl sse_decode_box_autoadd_time_control(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_time_control(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_8(deserializer));
  }

  @protected
  ClockState sse_decode_clock_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_whiteMs = sse_decode_u_64(deserializer);
    var var_blackMs = sse_decode_u_64(deserializer);
    var var_active = sse_decode_opt_box_autoadd_color(deserializer);
    var var_paused = sse_decode_bool(deserializer);
    return ClockState(
        whiteMs: var_whiteMs,
        blackMs: var_blackMs,
        active: var_active,
        paused: var_paused);
  }

  @protected
  ClockTickEvent sse_decode_clock_tick_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gameId = sse_decode_String(deserializer);
    var var_whiteMs = sse_decode_u_64(deserializer);
    var var_blackMs = sse_decode_u_64(deserializer);
    var var_active = sse_decode_opt_box_autoadd_color(deserializer);
    return ClockTickEvent(
        gameId: var_gameId,
        whiteMs: var_whiteMs,
        blackMs: var_blackMs,
        active: var_active);
  }

  @protected
  Color sse_decode_color(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Color.values[inner];
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  GameMode sse_decode_game_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return GameMode.values[inner];
  }

  @protected
  GameOverEvent sse_decode_game_over_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gameId = sse_decode_String(deserializer);
    var var_result = sse_decode_game_result(deserializer);
    var var_reason = sse_decode_game_status(deserializer);
    return GameOverEvent(
        gameId: var_gameId, result: var_result, reason: var_reason);
  }

  @protected
  GameResult sse_decode_game_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return GameResult.values[inner];
  }

  @protected
  GameSnapshot sse_decode_game_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gameId = sse_decode_String(deserializer);
    var var_fen = sse_decode_String(deserializer);
    var var_turn = sse_decode_color(deserializer);
    var var_inCheck = sse_decode_bool(deserializer);
    var var_status = sse_decode_game_status(deserializer);
    var var_result = sse_decode_game_result(deserializer);
    var var_history = sse_decode_list_move(deserializer);
    var var_legalMoves = sse_decode_Map_String_list_String_None(deserializer);
    var var_clock = sse_decode_opt_box_autoadd_clock_state(deserializer);
    var var_mode = sse_decode_game_mode(deserializer);
    var var_aiDifficulty = sse_decode_opt_box_autoadd_u_8(deserializer);
    var var_humanColor = sse_decode_opt_box_autoadd_color(deserializer);
    var var_lastMove = sse_decode_opt_box_autoadd_move(deserializer);
    return GameSnapshot(
        gameId: var_gameId,
        fen: var_fen,
        turn: var_turn,
        inCheck: var_inCheck,
        status: var_status,
        result: var_result,
        history: var_history,
        legalMoves: var_legalMoves,
        clock: var_clock,
        mode: var_mode,
        aiDifficulty: var_aiDifficulty,
        humanColor: var_humanColor,
        lastMove: var_lastMove);
  }

  @protected
  GameStatus sse_decode_game_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return GameStatus.values[inner];
  }

  @protected
  HumanColorChoice sse_decode_human_color_choice(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return HumanColorChoice.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Move> sse_decode_list_move(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Move>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_move(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, List<String>)> sse_decode_list_record_string_list_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, List<String>)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_list_string(deserializer));
    }
    return ans_;
  }

  @protected
  Move sse_decode_move(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_from = sse_decode_String(deserializer);
    var var_to = sse_decode_String(deserializer);
    var var_promotion = sse_decode_opt_box_autoadd_promotion(deserializer);
    var var_san = sse_decode_String(deserializer);
    var var_uci = sse_decode_String(deserializer);
    var var_captured = sse_decode_opt_box_autoadd_piece(deserializer);
    var var_isCheck = sse_decode_bool(deserializer);
    var var_isMate = sse_decode_bool(deserializer);
    var var_isCastle = sse_decode_bool(deserializer);
    var var_isEnPassant = sse_decode_bool(deserializer);
    return Move(
        from: var_from,
        to: var_to,
        promotion: var_promotion,
        san: var_san,
        uci: var_uci,
        captured: var_captured,
        isCheck: var_isCheck,
        isMate: var_isMate,
        isCastle: var_isCastle,
        isEnPassant: var_isEnPassant);
  }

  @protected
  MoveMadeEvent sse_decode_move_made_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gameId = sse_decode_String(deserializer);
    var var_mv = sse_decode_move(deserializer);
    var var_snapshot = sse_decode_game_snapshot(deserializer);
    return MoveMadeEvent(
        gameId: var_gameId, mv: var_mv, snapshot: var_snapshot);
  }

  @protected
  MoveResult sse_decode_move_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mv = sse_decode_move(deserializer);
    var var_snapshot = sse_decode_game_snapshot(deserializer);
    return MoveResult(mv: var_mv, snapshot: var_snapshot);
  }

  @protected
  NewGameOpts sse_decode_new_game_opts(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mode = sse_decode_game_mode(deserializer);
    var var_aiDifficulty = sse_decode_opt_box_autoadd_u_8(deserializer);
    var var_humanColor =
        sse_decode_opt_box_autoadd_human_color_choice(deserializer);
    var var_timeControl = sse_decode_opt_box_autoadd_time_control(deserializer);
    return NewGameOpts(
        mode: var_mode,
        aiDifficulty: var_aiDifficulty,
        humanColor: var_humanColor,
        timeControl: var_timeControl);
  }

  @protected
  ClockState? sse_decode_opt_box_autoadd_clock_state(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_clock_state(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Color? sse_decode_opt_box_autoadd_color(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_color(deserializer));
    } else {
      return null;
    }
  }

  @protected
  GameSnapshot? sse_decode_opt_box_autoadd_game_snapshot(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_game_snapshot(deserializer));
    } else {
      return null;
    }
  }

  @protected
  HumanColorChoice? sse_decode_opt_box_autoadd_human_color_choice(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_human_color_choice(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Move? sse_decode_opt_box_autoadd_move(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_move(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Piece? sse_decode_opt_box_autoadd_piece(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_piece(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Promotion? sse_decode_opt_box_autoadd_promotion(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_promotion(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TimeControl? sse_decode_opt_box_autoadd_time_control(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_time_control(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_8(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Piece sse_decode_piece(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_color = sse_decode_color(deserializer);
    var var_kind = sse_decode_piece_kind(deserializer);
    return Piece(color: var_color, kind: var_kind);
  }

  @protected
  PieceKind sse_decode_piece_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PieceKind.values[inner];
  }

  @protected
  PieceSet sse_decode_piece_set(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PieceSet.values[inner];
  }

  @protected
  Promotion sse_decode_promotion(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Promotion.values[inner];
  }

  @protected
  (String, List<String>) sse_decode_record_string_list_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_list_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  Settings sse_decode_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_appTheme = sse_decode_app_theme(deserializer);
    var var_boardTheme = sse_decode_board_theme(deserializer);
    var var_pieceSet = sse_decode_piece_set(deserializer);
    var var_accent = sse_decode_accent(deserializer);
    var var_soundEnabled = sse_decode_bool(deserializer);
    var var_soundVolume = sse_decode_f_32(deserializer);
    var var_showLegalMoves = sse_decode_bool(deserializer);
    var var_showCoordinates = sse_decode_bool(deserializer);
    var var_showLastMove = sse_decode_bool(deserializer);
    return Settings(
        appTheme: var_appTheme,
        boardTheme: var_boardTheme,
        pieceSet: var_pieceSet,
        accent: var_accent,
        soundEnabled: var_soundEnabled,
        soundVolume: var_soundVolume,
        showLegalMoves: var_showLegalMoves,
        showCoordinates: var_showCoordinates,
        showLastMove: var_showLastMove);
  }

  @protected
  TimeControl sse_decode_time_control(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_initialMs = sse_decode_u_64(deserializer);
    var var_incrementMs = sse_decode_u_64(deserializer);
    return TimeControl(initialMs: var_initialMs, incrementMs: var_incrementMs);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Map_String_list_String_None(
      Map<String, List<String>> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_list_string(
        self.entries.map((e) => (e.key, e.value)).toList(), serializer);
  }

  @protected
  void sse_encode_StreamSink_backend_event_Sse(
      RustStreamSink<BackendEvent> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_backend_event,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_accent(Accent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_ai_progress_event(
      AiProgressEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.gameId, serializer);
    sse_encode_u_32(self.depth, serializer);
    sse_encode_i_32(self.evalCp, serializer);
    sse_encode_list_String(self.pvSan, serializer);
  }

  @protected
  void sse_encode_api_error(ApiError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ApiError_GameNotFound(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case ApiError_IllegalMove(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case ApiError_InvalidInput(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case ApiError_Engine(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
      case ApiError_Internal(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_app_theme(AppTheme self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_backend_event(BackendEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case BackendEvent_MoveMade(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_move_made_event(field0, serializer);
      case BackendEvent_AiProgress(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_ai_progress_event(field0, serializer);
      case BackendEvent_GameOver(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_box_autoadd_game_over_event(field0, serializer);
      case BackendEvent_ClockTick(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_box_autoadd_clock_tick_event(field0, serializer);
    }
  }

  @protected
  void sse_encode_board_theme(BoardTheme self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_ai_progress_event(
      AiProgressEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ai_progress_event(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_clock_state(
      ClockState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_clock_state(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_clock_tick_event(
      ClockTickEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_clock_tick_event(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_color(Color self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_color(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_game_over_event(
      GameOverEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_game_over_event(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_game_snapshot(
      GameSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_game_snapshot(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_human_color_choice(
      HumanColorChoice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_human_color_choice(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_move(Move self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_move(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_move_made_event(
      MoveMadeEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_move_made_event(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_new_game_opts(
      NewGameOpts self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_new_game_opts(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_piece(Piece self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_piece(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_promotion(
      Promotion self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_promotion(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_settings(
      Settings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_settings(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_time_control(
      TimeControl self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_time_control(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self, serializer);
  }

  @protected
  void sse_encode_clock_state(ClockState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.whiteMs, serializer);
    sse_encode_u_64(self.blackMs, serializer);
    sse_encode_opt_box_autoadd_color(self.active, serializer);
    sse_encode_bool(self.paused, serializer);
  }

  @protected
  void sse_encode_clock_tick_event(
      ClockTickEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.gameId, serializer);
    sse_encode_u_64(self.whiteMs, serializer);
    sse_encode_u_64(self.blackMs, serializer);
    sse_encode_opt_box_autoadd_color(self.active, serializer);
  }

  @protected
  void sse_encode_color(Color self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_game_mode(GameMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_game_over_event(
      GameOverEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.gameId, serializer);
    sse_encode_game_result(self.result, serializer);
    sse_encode_game_status(self.reason, serializer);
  }

  @protected
  void sse_encode_game_result(GameResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_game_snapshot(GameSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.gameId, serializer);
    sse_encode_String(self.fen, serializer);
    sse_encode_color(self.turn, serializer);
    sse_encode_bool(self.inCheck, serializer);
    sse_encode_game_status(self.status, serializer);
    sse_encode_game_result(self.result, serializer);
    sse_encode_list_move(self.history, serializer);
    sse_encode_Map_String_list_String_None(self.legalMoves, serializer);
    sse_encode_opt_box_autoadd_clock_state(self.clock, serializer);
    sse_encode_game_mode(self.mode, serializer);
    sse_encode_opt_box_autoadd_u_8(self.aiDifficulty, serializer);
    sse_encode_opt_box_autoadd_color(self.humanColor, serializer);
    sse_encode_opt_box_autoadd_move(self.lastMove, serializer);
  }

  @protected
  void sse_encode_game_status(GameStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_human_color_choice(
      HumanColorChoice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_move(List<Move> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_move(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_list_string(
      List<(String, List<String>)> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_list_string(item, serializer);
    }
  }

  @protected
  void sse_encode_move(Move self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.from, serializer);
    sse_encode_String(self.to, serializer);
    sse_encode_opt_box_autoadd_promotion(self.promotion, serializer);
    sse_encode_String(self.san, serializer);
    sse_encode_String(self.uci, serializer);
    sse_encode_opt_box_autoadd_piece(self.captured, serializer);
    sse_encode_bool(self.isCheck, serializer);
    sse_encode_bool(self.isMate, serializer);
    sse_encode_bool(self.isCastle, serializer);
    sse_encode_bool(self.isEnPassant, serializer);
  }

  @protected
  void sse_encode_move_made_event(
      MoveMadeEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.gameId, serializer);
    sse_encode_move(self.mv, serializer);
    sse_encode_game_snapshot(self.snapshot, serializer);
  }

  @protected
  void sse_encode_move_result(MoveResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_move(self.mv, serializer);
    sse_encode_game_snapshot(self.snapshot, serializer);
  }

  @protected
  void sse_encode_new_game_opts(NewGameOpts self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_game_mode(self.mode, serializer);
    sse_encode_opt_box_autoadd_u_8(self.aiDifficulty, serializer);
    sse_encode_opt_box_autoadd_human_color_choice(self.humanColor, serializer);
    sse_encode_opt_box_autoadd_time_control(self.timeControl, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_clock_state(
      ClockState? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_clock_state(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_color(Color? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_color(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_game_snapshot(
      GameSnapshot? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_game_snapshot(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_human_color_choice(
      HumanColorChoice? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_human_color_choice(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_move(Move? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_move(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_piece(Piece? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_piece(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_promotion(
      Promotion? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_promotion(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_time_control(
      TimeControl? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_time_control(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_8(self, serializer);
    }
  }

  @protected
  void sse_encode_piece(Piece self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_color(self.color, serializer);
    sse_encode_piece_kind(self.kind, serializer);
  }

  @protected
  void sse_encode_piece_kind(PieceKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_piece_set(PieceSet self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_promotion(Promotion self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_record_string_list_string(
      (String, List<String>) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_list_String(self.$2, serializer);
  }

  @protected
  void sse_encode_settings(Settings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_app_theme(self.appTheme, serializer);
    sse_encode_board_theme(self.boardTheme, serializer);
    sse_encode_piece_set(self.pieceSet, serializer);
    sse_encode_accent(self.accent, serializer);
    sse_encode_bool(self.soundEnabled, serializer);
    sse_encode_f_32(self.soundVolume, serializer);
    sse_encode_bool(self.showLegalMoves, serializer);
    sse_encode_bool(self.showCoordinates, serializer);
    sse_encode_bool(self.showLastMove, serializer);
  }

  @protected
  void sse_encode_time_control(TimeControl self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.initialMs, serializer);
    sse_encode_u_64(self.incrementMs, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
