//! Placeholder for the flutter_rust_bridge crate. The actual bridge API
//! is defined in [`api`] and exposed via `flutter_rust_bridge_codegen`.
//!
//! See the `flutter/` directory for Dart side; bindings under
//! `flutter/lib/src/rust/` are generated by:
//!
//! ```bash
//! cd flutter && flutter_rust_bridge_codegen generate
//! ```

pub mod api;
pub mod platform;
