//! flutter_rust_bridge crate — exposes [`chess_core`] to the Flutter app.
//!
//! Dart bindings are generated by `flutter_rust_bridge_codegen` from
//! [`api`]; they live under `flutter/lib/src/rust/`.
//!
//! Architecture:
//!
//! - Dart calls `bridgeInit(...)` with a writable `dataDir` and a
//!   `StreamSink<BackendEvent>` once at startup.
//! - From then on the Dart UI calls the command-equivalent functions
//!   in [`api`] (one per legacy Tauri command) and listens to the
//!   single broadcast `Stream` for the four push events.
//! - The Stockfish spawner is selected at compile time by `cfg(target_os)`:
//!   - `linux` / `macos` / `windows`: spawn the bundled sidecar binary
//!     pulled out of the Flutter assets bundle.
//!   - `android`: extract the per-ABI binary from assets to `dataDir`
//!     on first use, then spawn it with `tokio::process`.
//!   - `ios`: [`chess_core::platform::NoStockfishSpawner`] — falls
//!     back to the custom Rust engine.

pub mod api;
pub mod platform;
pub(crate) mod broadcast;

pub mod frb_generated;

use std::sync::OnceLock;

use chess_core::session::SessionManager;

/// Globally shared session manager. Bridged commands borrow it
/// reentrantly; Dart sees one logical `chess_core` instance per process.
static SESSION: OnceLock<SessionManager> = OnceLock::new();

pub(crate) fn session() -> &'static SessionManager {
    SESSION
        .get()
        .expect("chess_bridge::api::bridge_init must be called before any command")
}

pub(crate) fn install_session(session: SessionManager) {
    let _ = SESSION.set(session);
}

pub(crate) fn try_session() -> Option<&'static SessionManager> {
    SESSION.get()
}
