//! Chess — Tauri 2 application library entry point.
//!
//! `lib.rs` wires up the API contract with `tauri-specta` so TypeScript
//! bindings are auto-generated into `src/lib/api/bindings.ts` on every
//! debug build, then runs the Tauri app.

pub mod api;
pub mod ai;
pub mod clock;
pub mod commands;
pub mod engine;
pub mod pgn;
pub mod session;

use tauri_specta::{collect_commands, collect_events, Builder};

use crate::api::{AiProgressEvent, ClockTickEvent, GameOverEvent, MoveMadeEvent};
use crate::session::SessionManager;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let specta_builder = Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::new_game,
            commands::legal_moves_from,
            commands::make_move,
            commands::request_ai_move,
            commands::undo_move,
            commands::resign,
            commands::offer_draw,
            commands::claim_draw,
            commands::load_pgn,
            commands::export_pgn,
            commands::set_clock,
            commands::pause_clock,
            commands::resume_clock,
            commands::get_settings,
            commands::set_settings,
        ])
        .events(collect_events![
            MoveMadeEvent,
            AiProgressEvent,
            GameOverEvent,
            ClockTickEvent,
        ]);

    #[cfg(debug_assertions)]
    specta_builder
        .export(
            specta_typescript::Typescript::default()
                .header("// AUTO-GENERATED by tauri-specta. Do not edit by hand.\n"),
            "../src/lib/api/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");

    let session_manager = SessionManager::new();

    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_dialog::init())
        .manage(session_manager.clone_handle())
        .invoke_handler(specta_builder.invoke_handler())
        .setup(move |app| {
            session_manager.set_app_handle(app.handle().clone());
            specta_builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running Chess application");
}
