//! Shared API contract between the Rust backend and the Svelte frontend.
//!
//! These types are the single source of truth. TypeScript bindings are
//! auto-generated by `tauri-specta` on every debug build into
//! `src/lib/api/bindings.ts`.
//!
//! IMPORTANT: Both subagents (frontend and backend) build against this
//! contract. Do not change a type's shape without updating both sides.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use specta::Type;

// ---------------------------------------------------------------------------
// Primitives
// ---------------------------------------------------------------------------

/// Algebraic square name, e.g. `"a1"` … `"h8"`.
pub type SquareStr = String;

/// Game identifier (UUID v4 string).
pub type GameId = String;

#[derive(Debug, Clone, Copy, Serialize, Deserialize, Type, PartialEq, Eq, Hash)]
#[serde(rename_all = "lowercase")]
pub enum Color {
    W,
    B,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, Type, PartialEq, Eq, Hash)]
#[serde(rename_all = "lowercase")]
pub enum PieceKind {
    P,
    N,
    B,
    R,
    Q,
    K,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, Type, PartialEq, Eq, Hash)]
pub struct Piece {
    pub color: Color,
    pub kind: PieceKind,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, Type, PartialEq, Eq, Hash)]
#[serde(rename_all = "lowercase")]
pub enum Promotion {
    N,
    B,
    R,
    Q,
}

// ---------------------------------------------------------------------------
// Moves & game snapshot
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct Move {
    pub from: SquareStr,
    pub to: SquareStr,
    pub promotion: Option<Promotion>,
    pub san: String,
    pub uci: String,
    pub captured: Option<Piece>,
    pub is_check: bool,
    pub is_mate: bool,
    pub is_castle: bool,
    pub is_en_passant: bool,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, Type, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum GameStatus {
    Active,
    Checkmate,
    Stalemate,
    DrawFiftyMove,
    DrawThreefold,
    DrawInsufficient,
    DrawAgreement,
    Resigned,
    TimeForfeit,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, Type, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum GameResult {
    White,
    Black,
    Draw,
    Ongoing,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct ClockState {
    pub white_ms: u64,
    pub black_ms: u64,
    pub active: Option<Color>,
    pub paused: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct GameSnapshot {
    pub game_id: GameId,
    pub fen: String,
    pub turn: Color,
    pub in_check: bool,
    pub status: GameStatus,
    pub result: GameResult,
    pub history: Vec<Move>,
    /// Map of source-square -> reachable target squares.
    pub legal_moves: HashMap<SquareStr, Vec<SquareStr>>,
    pub clock: Option<ClockState>,
    pub mode: GameMode,
    pub ai_difficulty: Option<u8>,
    pub human_color: Option<Color>,
    pub last_move: Option<Move>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct MoveResult {
    pub mv: Move,
    pub snapshot: GameSnapshot,
}

// ---------------------------------------------------------------------------
// New game / settings
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, Serialize, Deserialize, Type, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum GameMode {
    /// Human vs human (local).
    Hvh,
    /// Human vs AI.
    Hva,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, Type, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum HumanColorChoice {
    W,
    B,
    Random,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, Type)]
pub struct TimeControl {
    pub initial_ms: u64,
    pub increment_ms: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct NewGameOpts {
    pub mode: GameMode,
    /// Required when `mode == Hva`. Range 1..=10.
    pub ai_difficulty: Option<u8>,
    pub human_color: Option<HumanColorChoice>,
    pub time_control: Option<TimeControl>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, Type, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum BoardTheme {
    Wood,
    Slate,
    WoodRealistic,
    SlateRealistic,
    Marble,
    Emerald,
    Obsidian,
    Sandstone,
    Midnight,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, Type, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum AppTheme {
    Light,
    Dark,
    Black,
    CasualLight,
    CasualDark,
    LiquidGlass,
    Material,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, Type, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum PieceSet {
    Classic,
    Modern,
    Merida,
    Minimal,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, Type, PartialEq, Eq, Default)]
#[serde(rename_all = "snake_case")]
pub enum Accent {
    #[default]
    Walnut,
    Forest,
    Violet,
    Teal,
    Rose,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct Settings {
    pub app_theme: AppTheme,
    pub board_theme: BoardTheme,
    pub piece_set: PieceSet,
    #[serde(default)]
    pub accent: Accent,
    pub sound_enabled: bool,
    pub sound_volume: f32,
    pub show_legal_moves: bool,
    pub show_coordinates: bool,
    pub show_last_move: bool,
}

impl Default for Settings {
    fn default() -> Self {
        Self {
            app_theme: AppTheme::Light,
            board_theme: BoardTheme::Wood,
            piece_set: PieceSet::Merida,
            accent: Accent::Walnut,
            sound_enabled: true,
            sound_volume: 0.6,
            show_legal_moves: true,
            show_coordinates: true,
            show_last_move: true,
        }
    }
}

// ---------------------------------------------------------------------------
// Events (backend -> frontend)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
#[cfg_attr(feature = "tauri-events", derive(tauri_specta::Event))]
#[cfg_attr(feature = "tauri-events", tauri_specta(event_name = "move-made"))]
pub struct MoveMadeEvent {
    pub game_id: GameId,
    pub mv: Move,
    pub snapshot: GameSnapshot,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
#[cfg_attr(feature = "tauri-events", derive(tauri_specta::Event))]
#[cfg_attr(feature = "tauri-events", tauri_specta(event_name = "ai-progress"))]
pub struct AiProgressEvent {
    pub game_id: GameId,
    pub depth: u32,
    pub eval_cp: i32,
    pub pv_san: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
#[cfg_attr(feature = "tauri-events", derive(tauri_specta::Event))]
#[cfg_attr(feature = "tauri-events", tauri_specta(event_name = "game-over"))]
pub struct GameOverEvent {
    pub game_id: GameId,
    pub result: GameResult,
    pub reason: GameStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
#[cfg_attr(feature = "tauri-events", derive(tauri_specta::Event))]
#[cfg_attr(feature = "tauri-events", tauri_specta(event_name = "clock-tick"))]
pub struct ClockTickEvent {
    pub game_id: GameId,
    pub white_ms: u64,
    pub black_ms: u64,
    pub active: Option<Color>,
}

/// Aggregate enum for every push-style event the backend emits.
///
/// The Tauri shell unwraps this and calls `app.emit("...", payload)` with
/// the matching event name; the Flutter bridge fans this out to a
/// `flutter_rust_bridge::StreamSink`.
#[derive(Debug, Clone, Serialize, Deserialize, Type)]
#[serde(tag = "kind", rename_all = "kebab-case")]
pub enum BackendEvent {
    MoveMade(MoveMadeEvent),
    AiProgress(AiProgressEvent),
    GameOver(GameOverEvent),
    ClockTick(ClockTickEvent),
}

impl BackendEvent {
    /// The Tauri event name (kept in lockstep with the original `app.emit`
    /// strings so the legacy Svelte client keeps working).
    pub fn name(&self) -> &'static str {
        match self {
            BackendEvent::MoveMade(_) => "move-made",
            BackendEvent::AiProgress(_) => "ai-progress",
            BackendEvent::GameOver(_) => "game-over",
            BackendEvent::ClockTick(_) => "clock-tick",
        }
    }
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

#[derive(Debug, thiserror::Error, Serialize, Deserialize, Type)]
#[serde(tag = "kind", content = "message")]
pub enum ApiError {
    #[error("game not found: {0}")]
    GameNotFound(String),
    #[error("illegal move: {0}")]
    IllegalMove(String),
    #[error("invalid input: {0}")]
    InvalidInput(String),
    #[error("engine error: {0}")]
    Engine(String),
    #[error("internal error: {0}")]
    Internal(String),
}

pub type ApiResult<T> = Result<T, ApiError>;
